### ISSUE TITLE
core dumped when running it under Linux

### ISSUE THREAD

**Issue by yangjie-mineral** [HPSCIL/cuSTARFM#2]
Hi,

I compiled this binary under Ubuntu Linux 14.04, nVidia Xp, but it crashed when I ran it by './cuSTARFM parameters_exmaple.txt' (after changing the location of the files). I got:

�����ļ�Ӧ����STARFM_PARAMETER_END��β
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

Thanks!

**Comment by gisers** [comment]
There may be a bit of problem in memory usage when the input data is larger than total memory and I have made some changes.You can add my QQ994684265 for discuss

**Comment by yangjie-mineral** [comment]
The input data is TestData/M_2002_01_04.tif, TestData/L_2002_01_04.tif, and TestData/M_2002_02_12.tif., whose size should be 300x300x6. 
My GPU memory is 12G and my PC memory is 96G. I don't really think my memory is not enough. 

Unfortunately I can't install Windows in my PC to test it.

**Comment by gisers** [comment]
Strangely，I tested on Ubuntu Linux  just now and the test was successful.Maybe your file path is too long which more than the limit of 1000 char.You can test it in another folder,and I will increase the length limit of the file path.I can't find other reasons for unsuccess

**Comment by gisers** [comment]
Hi，have you solved your problem，I want to know what the problem is and do a little improvement.In addition，I want to know your version of CUDA and the version of GDAL.Thanks!

**Comment by yangjie-mineral** [comment]
Sorry, I just saw your reply. It's working now.

I found my nvidia driver got some conflict. Then I reinstalled the driver and the program didn't crash.
I have those library installed: libcuda1-384, libcudart5.5
GDAL is 1.10.1

Thanks, good job!
